# Copyright 2018 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause OR GPL-3.0-only
---
- hosts: 127.0.0.1
  connection: local
  become: yes
  collections:
    - mware.ansible_for_nsxt
  tasks:
    - name: Add Static Routes on a Logical Router
      vmware.ansible_for_nsxt.nsxt_logical_router_static_routes:
        hostname: "{{hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        validate_certs: False
        display_name: "static_route"
        logical_router_name: "SB-T0-GATEWAY-01"
        next_hops:
        - administrative_distance: '2'
          ip_address: 192.168.200.254
        network: 192.168.200.0/24
        state: "present"
